timemanager-kw/TimeManager

TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs
TimeManager/Data/Model/DateTimeBlock.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedTasks.cs
TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs

- #21 
- `DateTimeBlock.Differnece()` 정의 및 일부 private methods 정의

`TimeTable.Operations.WorkAndAvailableTimes` 구현

---

TimeManager/Data/Model/Task.cs

`Task` 내 타입 구현 (단일/장기)

---

TimeManager.sln
TimeManagerUnitTests/Properties/AssemblyInfo.cs
TimeManagerUnitTests/TimeManagerUnitTests.csproj
TimeManagerUnitTests/UnitTest1.cs
TimeManagerUnitTests/packages.config

`UnitTests` 프로젝트 생성

---

TimeManager.sln
TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs
TimeManager/Data/Model/DateTimeBlock.cs
TimeManager/Data/Model/ITimeTable.cs
TimeManager/Data/Model/Task.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedTasks.cs
TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs
TimeManager/Data/Model/TimeTable.cs
TimeManager/Data/Model/Week.cs
TimeManager/Extensions/DateTimeExtension.cs
TimeManager/TimeManager.csproj
TimeManagerUnitTests/Properties/AssemblyInfo.cs
TimeManagerUnitTests/TimeManagerUnitTests.csproj
TimeManagerUnitTests/UnitTest1.cs
TimeManagerUnitTests/packages.config

#28을 #18에 적용

---

TimeManager/Data/Model/Schedule.cs
TimeManager/Data/Repository/FileScheduleRepository.cs
TimeManager/TimeManager.csproj

FileScheduleRepository 구현

---

TimeManager/Data/Manager/IScheduleManager.cs
TimeManager/Data/Manager/ITaskManager.cs
TimeManager/Data/Manager/ITimeTableManager.cs
TimeManager/Data/Manager/ScheduleManager.cs
TimeManager/Data/Manager/TaskManager.cs
TimeManager/Data/Manager/TimeTableManager.cs
TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs
TimeManager/Data/Model/DateTimeBlock.cs
TimeManager/Data/Model/ITimeTable.cs
TimeManager/Data/Model/Schedule.cs
TimeManager/Data/Model/Task.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedTasks.cs
TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs
TimeManager/Data/Model/TimeTable.cs
TimeManager/Data/Model/Week.cs
TimeManager/Data/Model/WeeklyDateTimeBlock.cs
TimeManager/Data/Repository/FileScheduleRepository.cs
TimeManager/Data/Repository/IScheduleRepository.cs
TimeManager/Data/Repository/ITaskRepository.cs
TimeManager/Data/Repository/ITimeTableRepository.cs

(hotfix) `.Data` 내 접근 제한자 `public`으로 수정

---

TimeManager/Data/Manager/IScheduleManager.cs
TimeManager/Data/Manager/ITaskManager.cs
TimeManager/Data/Manager/ITimeTableManager.cs
TimeManager/Data/Manager/ScheduleManager.cs
TimeManager/Data/Manager/TaskManager.cs
TimeManager/Data/Manager/TimeTableManager.cs
TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs
TimeManager/Data/Model/DateTimeBlock.cs
TimeManager/Data/Model/ITimeTable.cs
TimeManager/Data/Model/Schedule.cs
TimeManager/Data/Model/Task.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedTasks.cs
TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs
TimeManager/Data/Model/TimeTable.cs
TimeManager/Data/Model/Week.cs
TimeManager/Data/Model/WeeklyDateTimeBlock.cs
TimeManager/Data/Repository/FileScheduleRepository.cs
TimeManager/Data/Repository/IScheduleRepository.cs
TimeManager/Data/Repository/ITaskRepository.cs
TimeManager/Data/Repository/ITimeTableRepository.cs
TimeManager/TimeManager.csproj

#34 작업내역 반영

---

TimeManager/Data/Repository/FileTaskRepository.cs
TimeManager/TimeManager.csproj

FileTaskRepository 구현

---

TimeManager/Controls/WeeklyTimeTableControl.Designer.cs
TimeManager/Controls/WeeklyTimeTableControl.cs
TimeManager/Controls/WeeklyTimeTableControl.resx
TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs
TimeManager/Data/Model/DateTimeBlock.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs
TimeManager/Data/Model/TimeTable.Operations.AssignedTasks.cs
TimeManager/Data/Model/Week.cs
TimeManager/Extensions/DateTimeExtension.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.Designer.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.resx
TimeManager/TimeManager.csproj

`WeeklyTimeTableControl` 커스텀 컨트롤 구현

---

TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs
TimeManager/Data/Model/DateTimeBlock.cs
TimeManager/Data/Repository/FileTimeTableRepository.cs
TimeManager/TimeManager.csproj

FileTimeTableRepository 구현

---

TimeManager/Data/Model/DateTimeBlock.cs
TimeManager/Data/Repository/FileScheduleRepository.cs

FileScheduleRepository 수정

---

TimeManager/Controls/WeeklyTimeTableControl.Designer.cs
TimeManager/Forms/AddScheduleForm.Designer.cs
TimeManager/Forms/AddScheduleForm.resx
TimeManager/Forms/MainForm.Designer.cs
TimeManager/Forms/MainForm.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.Designer.cs
TimeManager/TimeManager.csproj

fit: Visual Update

---

TimeManager/Controls/WeeklyTimeTableSelectableControl.Designer.cs
TimeManager/Controls/WeeklyTimeTableSelectableControl.cs
TimeManager/Data/Model/Task.cs
TimeManager/Data/Model/longTermProperties.cs
TimeManager/TimeManager.csproj

Task 구조 수정 작업

---

TimeManager/Controls/EventArgs/WeeklyTimeTableControlItemEventArgs.cs
TimeManager/Controls/WeeklyTimeTableControl.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.Designer.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.cs
TimeManager/TimeManager.csproj

- #61 
- `WeeklyTimeTableControl` 컨트롤의 이벤트 속성에 `ItemSelected`가 추가되었습니다. 이 이벤트를 이용해 사용자가 컨트롤 내에서 선택한 아이템의 정보를 받아올 수 있습니다. 구현 예시는 `TimeManager.Forms.Tests.TestWeeklyTimeTableControl`를 참고하시면 됩니다.

`WeeklyTimeTableControl`에 아이템 선택/이벤트 및 이름 표시 추가

---

TimeManager/Forms/MainForm.Designer.cs
TimeManager/Forms/MainForm.cs

feat: open add task form logic

---

TimeManager/Data/Manager/IScheduleManager.cs
TimeManager/Data/Manager/ITaskManager.cs
TimeManager/Data/Manager/ScheduleManager.cs
TimeManager/Data/Manager/TaskManager.cs

`TaskManager`와 `ScheduleManager`에 `GetById()` 구현

---

TimeManager/Data/Model/TimeTable.Operations.AssignedTasks.cs

TimeTable.Operations.AssignedTasks 구현

---

TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs

AssignedSchedule 및 AssignedTask 수정

---

TimeManager/Data/Model/AssignedSchedule.cs
TimeManager/Data/Model/AssignedTask.cs

AssignedSchedule 및 AssignedTask수정

---

TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs

TimeTable.Operations.AssignedSchedules 구현

---

TimeManager/Data/Repository/FileTaskRepository.cs

FileTaskRepository 수정

---

TimeManager/Data/Repository/FileTimeTableRepository.cs

FileTimeTableRepository 수정

---

TimeManager/Scheduler/Scheduler.cs
TimeManager/Scheduler/ThunderScheduler.cs
TimeManager/TimeManager.csproj

'ThunderScheduler' 구현

---

TimeManager/Data/Repository/FileTaskRepository.cs
TimeManager/Forms/AddScheduleForm.cs
TimeManager/Forms/AddTaskForm.Designer.cs
TimeManager/Forms/AddTaskForm.cs
TimeManager/Forms/EditAvailableTimeForm.Designer.cs
TimeManager/Forms/EditAvailableTimeForm.cs
TimeManager/Forms/MainForm.Designer.cs
TimeManager/Forms/MainForm.cs
TimeManager/Forms/MainForm.resx

17 mainform

---

TimeManager/Forms/MainForm.cs

feat: set last task and schedule id

---

TimeManager/Forms/MainForm.cs

feat: 그 셀에 그리는 부분 조금 수정했음

---

TimeManager/Controls/WeeklyTimeTableControl.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.Designer.cs
TimeManager/Forms/Tests/TestWeeklyTimeTableControl.cs
TimeManager/Scheduler/ThunderScheduler.cs
TimeManagerUnitTests/Scheduler/ThunderSchedulerStrategyUnitTests.cs

`WeeklyTimeTableControl` 내 `Manager`를 이용해 `Name` 가져오도록 수정

---

TimeManager/Data/Repository/FileScheduleRepository.cs
TimeManager/Data/Repository/FileTaskRepository.cs
TimeManager/Data/Repository/FileTimeTableRepository.cs
TimeManager/Forms/MainForm.Designer.cs
TimeManager/Forms/MainForm.cs
TimeManager/Forms/MainForm.resx
TimeManager/Program.cs

FileRepository 수정

---

TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs
TimeManager/Scheduler/ThunderScheduler.cs
TimeManager/Scheduler/ThunderSchedulerStrategy.cs

ThunderSchedulerStrategy 구현(정기 제외)

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

ThunderScheduler/ ThunderSchedulerStarategy 구현

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

ThunderSchedulerStrategy 잔바리 오류 수정

---

TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs

`GetWeeklyWorkTimes()` 시 과거로 가다가 SOF 나는 문제

---

TimeManager/Forms/MainForm.cs

feat: 업무 수정 수정

---

TimeManager/Controls/WeeklyTimeTableControl.cs

`WeeklyTimeTableControl` 초기 로드 시 현재 시간 기준 자동 스크롤 이동

---

TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs

- #120 
- `GetDailyAvailableTimes()` 시 현재 주차의 스케줄을 빼도록 수정

`GetAvailableTimesInBlock()` 내 올바르지 않은 날짜 정보 들어가는 문제

---

TimeManager/Data/Model/ITimeTable.cs
TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs
TimeManager/Scheduler/ThunderSchedulerStrategy.cs

fix - GetAvailableTimesInDaysBlock 변경

---

TimeManager/Data/Model/ITimeTable.cs

fix-잘못된이름수정

---

TimeManager/Forms/AddTaskForm.cs
TimeManager/Forms/MainForm.cs

fix: 듀레이션 수정

---

TimeManager/Forms/MainForm.cs

fix: 듀레이션 수정 다함

---

TimeManager/Forms/MainForm.cs

feat: 알고리즘 돌리고 파일에 어사인 저장하는거

---

TimeManager/Forms/MainForm.cs

fix: 그 어사인드 하는거 한칸씩 안채워지던거 일단 수정해봄

---

TimeManager/Forms/MainForm.cs

fix: 색칠 수정함

---

TimeManager/Forms/MainForm.cs

fix: 24시 추가함

---

TimeManager/Forms/MainForm.cs

fix: 같은 일정이나 업무는 같은 색으로 수정

---

TimeManager/Scheduler/ThunderScheduler.cs
TimeManager/Scheduler/ThunderSchedulerStrategy.cs

ThunderSchedulerStrategy RandomArrange 쪼금 많이 수정

---

TimeManager/Data/Repository/FileScheduleRepository.cs
TimeManager/Data/Repository/FileTaskRepository.cs

fix: for문 수정

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

ThunderSchedulerStrategy 진짜 많이 왔다 최선을 다하자

---

TimeManager/Scheduler/ThunderScheduler.cs
TimeManager/Scheduler/ThunderSchedulerStrategy.cs

feat- 정기 schedule 등록 기능 구현

---

TimeManager/Forms/MainForm.cs

fix: 그 파일에 보낼때 이상했던거 수정

---

TimeManager/Forms/AddTaskForm.Designer.cs
TimeManager/Forms/AddTaskForm.cs
TimeManager/Forms/MainForm.Designer.cs
TimeManager/Forms/MainForm.cs
TimeManager/Forms/MainForm.resx

fix: 마감일 포함 플래그 삭제했습니다

---

TimeManager/Forms/MainForm.cs

fix: 일정 추가하면 바로 뷰에 최신화할 수 있게 만들었음

---

TimeManager/Controls/WeeklyTimeTableControl.cs
TimeManager/Data/Model/Week.cs
TimeManager/Forms/MainForm.cs

`WeeklyTimeTableControl` 내 요일에 해당하는 날짜 추가

---

TimeManager/Data/Repository/FileTimeTableRepository.cs
TimeManager/Scheduler/ThunderScheduler.cs

FileTimeTableRepository와 ThunderScheduler의 schedule assign해주는 부분 수정

---

TimeManager/Scheduler/ThunderScheduler.cs

ThunderScheduler 메서드 수정

---

TimeManager/Data/Model/ITimeTable.cs
TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs

`TimeTable` 내 `IsAvailable` 제거

---

TimeManager/Forms/MainForm.cs

`MoveScrollToNow()` 인덱스 범위 수정

---

TimeManager/Forms/MainForm.cs

fix: 리무브를 포이치에서 해버렸네. 태스크리스트 포이치 돌릴 때 중간에서 리무브하는거를 지움

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

가용시간 초과 메세지박스로 교체

---

TimeManager/Controls/WeeklyTimeTableSelectableControl.Designer.cs
TimeManager/Forms/EditAvailableTimeForm.Designer.cs

`WeeklyTimeTableSelectableControl` 내 기본 너비 조절

---

TimeManager/Scheduler/ThunderScheduler.cs

fix: endDateTime = limitDate로 수정

---

TimeManager/Scheduler/ThunderScheduler.cs

feat AssignedTask가 중복되던 오류 해결

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

`LongTerm Task` 배치 로직 수정

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

`Schedule()` 시 `days`가 빈 배열이 되는 문제 해결

---

TimeManager/Forms/MainForm.cs

fix: 셀에서 선택했을 때 값이 -1일 경우를 생각 안해서 다시 수정

---

TimeManager/Data/Repository/FileTimeTableRepository.cs

fix: Update메서드 수정

---

TimeManager/Forms/MainForm.cs

fix: 파일 수정하는 부분을 조건문 바깥으로 빼서 수정함

---

TimeManager/Scheduler/ThunderScheduler.cs

fix Schedule save 및 메서드를 통한 처리

---

TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs

`ReassignSchedule()` 시 없는 경우에도 Assign되도록 수정

---

TimeManager/Data/Model/TimeTable.Operations.WorkAndAvailableTimes.cs

(hotfix) `WorkTime` 및 `Schedule` 블럭 리스트 형태로 변환

---

TimeManager/Data/Model/DateTimeBlock.cs

fix: Difference 메서드 수정

---

TimeManager/Scheduler/ThunderScheduler.cs

정기 일정 안 들어가는 문제 해결

---

TimeManager/Data/Model/TimeTable.Operations.AssignedSchedules.cs

`ReassignSchedule()`에서 기존 스케줄 완전 제거

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

FIX LongTermTask 문제 드디어 해결

---

TimeManager/Data/Model/TimeTable.Operations.AssignedTasks.cs

`ReassignTask()`에서 기존 태스크 완전 제거

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

feat 확률 조정 // 가용시간에 대해 랜덤함수를 활용하여 task가 중간위치에도 올 수 있도록 설정하였음. 진짜 끝.

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

fix 정기 오류나는 부분 해결

---

TimeManager/Scheduler/ThunderSchedulerStrategy.cs

`Debug` 출력문 제거
